### ISSUE TITLE
Fix CITATION.cff

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/software-support-essentials#28]
The citation file for this project should be amended: it is still the CITATION.cff for the EUCP storyboards project. This issue can be used to collect people involved in the project who should be included on the citation:

## Framework
All included in the current CITATION.cff were involved in the original Storyboards page, and should therefore be included in the new CITATION.cff file. That said @Peter9192, ~@SarahAlidoost~, @geek-yang, ~@sverhoeven~; let me know if you would *not* like to be included!

Also:
@JaroCamphuijsen (orcid: 0000-0002-8928-7831 )
@raar1 (orcid: 0000-0002-9984-2720 )

## Content
@mkuzak (orcid: ... )
@lourensveen (orcid: 0000-0002-6311-1168)

... more to come, let's use this issue to collect information for now.

**Comment by JaroCamphuijsen** [comment]
Hoi Barbara,
Hier is mijn ORCID: 0000-0002-8928-7831

Groetjes Jaro
________________________________
From: Barbara Vreede ***@***.***>
Sent: 20 March 2023 12:18
To: esciencecenter-digital-skills/software-support-essentials ***@***.***>
Cc: Jaro Camphuijsen ***@***.***>; Mention ***@***.***>
Subject: [esciencecenter-digital-skills/software-support-essentials] Fix CITATION.cff (Issue #28)


The citation file for this project should be amended: it is still the CITATION.cff for the EUCP storyboards project. This issue can be used to collect people involved in the project who should be included on the citation:

Framework

All included in the current CITATION.cff were involved in the original Storyboards page, and should therefore be included in the new CITATION.cff file. That said @Peter9192<https://github.com/Peter9192>, @SarahAlidoost<https://github.com/SarahAlidoost>, @geek-yang<https://github.com/geek-yang>, @sverhoeven<https://github.com/sverhoeven>; let me know if you would not like to be included!

Also:
@JaroCamphuijsen<https://github.com/JaroCamphuijsen> (orcid: ... )
@raar1<https://github.com/raar1> (orcid: ... )

Content

@mkuzak<https://github.com/mkuzak> (orcid: ... )
@LourensVeen<https://github.com/LourensVeen> (orcid: ... )

... more to come, let's use this issue to collect information for now.

**Comment by raar1** [comment]
Hi! Here's mine: 0000-0002-9984-2720

**Comment by SarahAlidoost** [comment]
@bvreede please remove me as I did not contribute to this project.

**Comment by Peter9192** [comment]
Cool developments! I'd love to have an opportunity to attend a demo or so

**Comment by sverhoeven** [comment]
Also I would not like to be included.

**Comment by bvreede** [comment]
@geek-yang and @Peter9192 Good to know! We don't have demos planned per se, but I'd love to have your feedback. I'll schedule something :)

**Comment by LourensVeen** [comment]
I'm 0000-0002-6311-1168
