### ISSUE TITLE
Construct pre-workshop survey for June workshop

### ISSUE THREAD

**Issue by raar1** [esciencecenter-digital-skills/software-support-essentials#44]
In order to get some idea of what sort of crowd will be at our trial run workshop in June, we would like to send a survey similar to the one used in our carpentries workshops.

@bvreede @JaroCamphuijsen Please think of any specific questions you would like to ask, and add them below. This needs to be finished by next week (19 April) so that we can send it along with the first email to participants.

**Comment by bvreede** [comment]
I would like to know the level of their technical skills. E.g., experience with:
- scripting languages (R/Python/Julia/Matlab/ ...)
- version control (git and github)
- executable notebooks (e.g. RMarkdown, jupyter notebook)
It would be good to emphasize that this is not experience we expect them to have, but really to check what background they have.

**Comment by bvreede** [comment]
Also experience with:
- FAIR data
- Data management plans
- Software management plans

**Comment by bvreede** [comment]
The questions asked in the end were:
- How familiar are you with (not at all/not so/somewhat/very/extremely):
  - Version control
  - Software licenses
  - Software testing
  - Software documentation
  - Software packaging
  - Software sustainability
  - Software citation
- In your daily work, do you get questions about (none/some/often):
  - Data science workflows
  - Version control
  - Software best practices
  - Data storage
  - Software packaging
  - Software sustainability
  - Software/code optimization
  - High performance computing
  - Reproducible code
  - Software citation
  - Testing and continuous integration
  - Containers
- Our workshop will be about FAIR software and Software Management Plans. What subject(s) or question(s) will need to be addressed to make the workshop a success for you?
- Is there a piece of software you would like to use as an example during the course? If so, please link to it here. (Note: submitting it here does not guarantee that we will be able to discuss it!)
- Why are you participating in this workshop (multiple choice):
  - To learn new skills
  - To refresh or review my skills
  - To learn skills that I can apply to my current work
  - To learn skills that I can apply to my work in the future
  - To learn skills that will help me get a job or a promotion
  - As a requirement for my program or current position
